version: 0.8.0

namespace: infrastructure-admin
project: infrastructure-admin

services:
  - name: infrastructure-admin
    image: ghcr.io/markmorcos/infrastructure-admin
    context: admin
    port: 3000
    serviceAccountName: infrastructure-admin
    env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: DATABASE_URL
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: JWT_SECRET
      - name: GITHUB_PAT
        valueFrom:
          secretKeyRef:
            name: github-credentials
            key: GITHUB_PAT
    ingress:
      host: admin.morcos.tech
      path: /
      pathType: Prefix
