name: apply-k8s

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: ["k8s/**"]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure VPN
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply k8s manifests
        run: KUBECONFIG=~/.kube/config kubectl apply -f k8s/
